### ISSUE TITLE
Adding this to Arduino 8266

### ISSUE THREAD

**Issue by plerup** [plieningerweb/esp8266-software-uart#1]
Is it possible to add this to the Arduino 8266 project (https://github.com/esp8266/Arduino) and if so, how? Thanks and BR /Peter Lerup

**Comment by plieningerweb** [comment]
Hey Peter,

thank you for the idea. 
I think it is possible, for sure. Unfortunately, right now I do not have the time to port and test it. Maybe later in August this year. Did you try to run it on EspArduino? Let me know, if you get any further with SoftwareSerial and EspArduino! :+1:

**Comment by HamedRoshanfekr** [comment]
Hi
actually I need this library to work in arduino ide.

**Comment by surfcoders** [comment]
Same here.  It would be wonderful if it can work on the Arduino ESP8266 IDE.  I tried adding the c and h files to the same local path of my INO Arduino project, referenced the h file there and it gives me compile errors (first one is "ets_sys.h:149:32: error: unknown type name 'size_t'".  My guess is that there are some additional library headers needed in order to run under the Arduino IDE.

**Comment by plerup** [comment]
I have just made an implementation of SoftwareSerial for the Arduino ESP8266. Try it if you like from:
https://github.com/plerup/espsoftwareserial

**Comment by surfcoders** [comment]
Thank you so much!!! Works great!!!  Keep you posted of any issues.
